version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GCS_BUCKET: ${GCS_BUCKET}
      GOOGLE_APPLICATION_CREDENTIALS: ${GCS_CREDENTIAL}
    volumes:
      - ./app:/app
